include: "rules/readsets.smk"
include: "rules/assemblies.smk"


def generate_outputs():
    outputs = []
    has_nanopore = len(config["nanopore_input_file"]) > 0
    has_pacbio = len(config["pacbio_input_file"]) > 0
    has_hic = len(config["hic_r1"]) > 0 and len(config["hic_r2"]) > 0

    if has_nanopore:
        outputs.append("Reads/nanopore_full.fastq")
        outputs.append("Reads/nanopore_full.stats")

        if "FULL" in config["readset_list"]:
            if "HIFIASM" in config["assemblers_list"]:
                outputs.append("Assembly/nanopore/Hifiasm/full/hap1.fasta")
                outputs.append("Assembly/nanopore/Hifiasm/full/hap2.fasta")
                outputs.append("Assembly/nanopore/Hifiasm/full/haploid.fasta")
            if "NEXTDENOVO" in config["assemblers_list"]:
                outputs.append("Assembly/nanopore/Nextdenovo/full/full.fasta")
            if "FLYE" in config["assemblers_list"]:
                outputs.append("Assembly/nanopore/Flye/full/full.fasta")
    
        if "LONGEST" in config["readset_list"]:
            outputs.append("Reads/nanopore_longest.fastq")
            outputs.append("Reads/nanopore_longest.stats")
            if "FLYE" in config["assemblers_list"]:
                outputs.append("Assembly/nanopore/Flye/longest/longest.fasta")
    
        if "FILTLONG" in config["readset_list"]:
            outputs.append("Reads/nanopore_filtlong.fastq")
            outputs.append("Reads/nanopore_filtlong.stats")
            if "FLYE" in config["assemblers_list"]:
                outputs.append("Assembly/nanopore/Flye/filtlong/filtlong.fasta")


    if has_pacbio:
        outputs.append("Reads/pacbio_full.fastq")
        outputs.append("Reads/pacbio_full.stats")
        
        if "HIFIASM" in config["assemblers_list"]:
            outputs.append("Assembly/pacbio/Hifiasm/full/hap1.fasta")
            outputs.append("Assembly/pacbio/Hifiasm/full/hap2.fasta")
            outputs.append("Assembly/pacbio/Hifiasm/full/haploid.fasta")

        if "NEXTDENOVO" in config["assemblers_list"]:
            outputs.append("Assembly/pacbio/Nextdenovo/full/full.fasta")


    if has_pacbio and has_nanopore:
        outputs.append("Assembly/hybrid/Hifiasm/full/hap1.fasta")
        outputs.append("Assembly/hybrid/Hifiasm/full/hap2.fasta")
        outputs.append("Assembly/hybrid/Hifiasm/full/haploid.fasta")

    
    if has_hic:
        if has_pacbio:
            outputs.append("Assembly/pacbio_hic/Hifiasm/full/hap1.fasta")
            outputs.append("Assembly/pacbio_hic/Hifiasm/full/hap2.fasta")
            outputs.append("Assembly/pacbio_hic/Hifiasm/full/haploid.fasta")
        if has_nanopore:
            outputs.append("Assembly/nanopore_hic/Hifiasm/full/hap1.fasta")
            outputs.append("Assembly/nanopore_hic/Hifiasm/full/hap2.fasta")
            outputs.append("Assembly/nanopore_hic/Hifiasm/full/haploid.fasta")
        if has_pacbio and has_nanopore:
            outputs.append("Assembly/hybrid_hic/Hifiasm/full/hap1.fasta")
            outputs.append("Assembly/hybrid_hic/Hifiasm/full/hap2.fasta")
            outputs.append("Assembly/hybrid_hic/Hifiasm/full/haploid.fasta")


            
    return outputs


rule all:
    input: generate_outputs()
